### ISSUE TITLE
Login failed: Authentication service unavailable.

### ISSUE THREAD

**Issue by jakefisher** [GeyserMC/MCProtocolLib#99]
Any attempt to connect to an authenticated server with the example code results in:

```
Version: 1.8, 47
Player Count: 0 / 6
Players: []
Description:
Icon: null
Server ping took 1022ms
Successfully authenticated user.
Disconnected: Login failed: Authentication service unavailable.
```

Server output:

```
[15:43:22] [Server thread/INFO]: com.mojang.authlib.GameProfile@48e65d42[id=<null>,name=[USERNAME],properties={},legacy=false] (/xx.xx.xx.xx:54774) lost connection: Disconnected
```

Is this just my incompetence? Everything works if the server is in offline mode.

**Comment by Steveice10** [comment]
Should be fixed as of https://github.com/Steveice10/MCAuthLib/commit/4e46dcd74fa93570efc46f86b6f84c2e027188fc

**Comment by AustinLMayes** [comment]
This is still happening.

**Comment by Steveice10** [comment]
Minecraft's session service seems to be having issues right now.

**Comment by AustinLMayes** [comment]
Sessions are up, can login fine with a normal client, still happening.

**Comment by Steveice10** [comment]
Working fine for me. What's the stack trace of the exception in the DisconnectedEvent?

**Comment by AustinLMayes** [comment]
I don't get a stack trace, I just get: `Disconnected: Login failed: Authentication service unavailable.
`

**Comment by Steveice10** [comment]
DisconnectedEvent contains a method, getCause, that returns a Throwable. Print out its stack trace.

**Comment by AustinLMayes** [comment]
```
Successfully authenticated user.
java.lang.NullPointerException
    at me.austinlm.mcai.Main$1.disconnected(Main.java:71)
    at org.spacehq.packetlib.event.session.DisconnectedEvent.call(DisconnectedEvent.java:65)
    at org.spacehq.packetlib.tcp.TcpSession.callEvent(TcpSession.java:125)
Disconnected: Login failed: Authentication service unavailable.
    at org.spacehq.packetlib.tcp.TcpSession$2.operationComplete(TcpSession.java:242)
    at org.spacehq.packetlib.tcp.TcpSession$2.operationComplete(TcpSession.java:239)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
    at io.netty.util.concurrent.DefaultPromise.notifyLateListener(DefaultPromise.java:621)
    at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:138)
    at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
    at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
    at org.spacehq.packetlib.tcp.TcpSession.disconnect(TcpSession.java:239)
    at org.spacehq.packetlib.tcp.TcpClientSession.disconnect(TcpClientSession.java:127)
    at org.spacehq.packetlib.tcp.TcpSession.disconnect(TcpSession.java:221)
    at org.spacehq.packetlib.tcp.TcpSession.disconnect(TcpSession.java:216)
    at org.spacehq.mc.protocol.ClientListener.packetReceived(ClientListener.java:61)
    at org.spacehq.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:50)
    at org.spacehq.packetlib.tcp.TcpSession.callEvent(TcpSession.java:125)
    at org.spacehq.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:43)
    at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:316)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
    at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:389)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:243)
    at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:389)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:243)
    at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:389)
    at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:389)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:956)
    at io.netty.channel.oio.AbstractOioByteChannel.doRead(AbstractOioByteChannel.java:147)
    at io.netty.channel.oio.AbstractOioChannel$1.run(AbstractOioChannel.java:44)
    at io.netty.channel.ThreadPerChannelEventLoop.run(ThreadPerChannelEventLoop.java:52)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:724)
```

**Comment by Steveice10** [comment]
You are not on the latest commit of MCProtocolLib. Please update and try again.

**Comment by AustinLMayes** [comment]
I updated, sessions are down again, I'll post again if the update hasn't fixed my issue.
